# Generated by Django 6.0.1 on 2026-02-02 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0002_order_payment_confirmed'),
        ('products', '0004_remove_product_has_preowned_option_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_weeks', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('bought_out', 'Bought Out'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('order_line_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_record', to='checkout.orderlineitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
