# Generated by Django 6.0.1 on 2026-02-04 01:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
