# Generated by Django 6.0.1 on 2026-01-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_preowned_option',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_rentable',
        ),
    ]
